[project]
name = "bilibili-subtitle"
version = "0.1.0"
description = "Extract Bilibili subtitles or transcribe audio to generate transcripts."
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = "3.11.*"
pip = "*"
ffmpeg = "*"
